env:
  global:
  - secure: uqEBilXblpKdEIMH701+Su5ceycbs5b09XkDQe3lc6MU8AQMlIw4RSxsE0oJ0z5qmR2SlSfH4zsr9rdO5CnON0uim8YJw5UsdutGszT8ThUx83ds1GdYWc6jUMagncYiJeSrrJtyysSIUdkAdqwiwnBq4mt1PYK626kKcJCw4UGhC/eOaof9bKec+ynm8FZHYMrRCLJyGIaqevn/z9KfKxKtZ/1qUpzVOqfutM9DqvGMvp/3KZAjU+mvOdb7U3AU6BWOu5Lu29zgUdeCaPNV5/WESPW4VrK3TEB5zkN+mwrfdYNpnDCsaywt4Hr20y+WQsC+DpWzg5/GsRSvYsNQwsueHUQQ6ApdSj/VlpEkHZ/hx9o1EPcZE+8vCzTrm5uVVnxtIVAs354kzg/MLyJIxVgOxhvtjw33zVTPJr8ntAhrkt7TAI8Epal724qT8AmfnqvQNni27H7Rdd9YxVnu+tMyg1d3K5om65Vo94FZUQbchkxo5Fiv7Cb901+LChjnaiWBrSZndOo9IVvyxZgVHwvGi+oSX9qs6Wi8p6SQr269wkg0LWgAUHYUoAUXVGTjWECNwmel2JHS1nIhZqb5653OvjUsDOlQbCnvFD5XX4zdM+Qh/eKB3iLs7nuo8oCfyAHJblPdYyyeE1dbciB80DTbqDFgOgWvjHiAIFqko8I=
  - secure: iJBn3AheegTh+d//I5JyvbTr5v5Sx6Opi+QjAX1vvckoJvaW4STqyC9E9v6HMBuzcIj/zt+rB+A7zyDqpbXon13+MXcyxQLbLc9oL1q7zBB6GVZDPWbPuEuA6iECdD34isW13NqDvtcN5e6UuyZTTwf0MAAVMBQs1u9LYLGQVgnip4hC9jkLz/PJfLlsLmVAL64oVZhhQUhI7l+DwYb1lzA9MZ2zGNjkRZj4kRlucqL9Brm3JPGfAPHTHFS3d/oXDjhar2ZcGBsNrlnj5Cxwb+SEEXx0Z/RMkznm4nZbQ0bdHntP5EZp2icNUAI1ZE0PjymIVrP7RDRO9Cy6ciqn0Z4/zkUZx7w+QsYVsp0OVUUJxoK4UM9Ozqi7eFbrhvWX/RG30h4EhMdZCR+prKkxyZBGTFzJX/67Uvsgzi58v32FrZZYZ15A9Zo60k3f94z9YvXGmzkx5qA7aFUG0/aDMDoN85arhtCMT/LMh6yI+nuoKDV5ygGNnNOYz68c9JT9KUnxve0qnRchZpLUi2b+WTmPMNoCTxd1osCtsGCSaMcPLeMLjNlM7Nwl9RoK8ckH6hL4VOGsv1b0FwkOwWbrpdoWpL8U6cohSn1BFFNrWNXgDPwJYNCbKMHC09OKNPvixHJkq6+GJJTEpiwPfOR/zY40u948QA3vOyx8TztGMNc=
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_40d7860e3fb5_key -iv $encrypted_40d7860e3fb5_iv
  -in config.json.enc -out config.json -d
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
script:
- echo 'I should write some tests...'
- eval $(aws ecr get-login --region us-west-2)
- docker build -t taco-bot-web:latest -t taco-bot-web:1.0.$TRAVIS_BUILD_NUMBER -t "869640726279.dkr.ecr.us-west-2.amazonaws.com/taco-bot-web:latest" .
- docker push "869640726279.dkr.ecr.us-west-2.amazonaws.com/taco-bot-web:latest"
